# Generated by Django 5.0.14 on 2026-06-22 16:49

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.TenantUserManager()),
            ],
        ),
    ]
